image: node:22-alpine

stages:

pages:
    stage: deploy
    cache:
        paths:
            - node_modules/
    script:
        - yarn install
        - yarn build
    artifacts:
        paths:
            - public
    rules:
        - if: '$CI_COMMIT_BRANCH == "main"'
          changes:
              - src/**/*
              - yarn.lock
              - .gitlab-ci.yml
